# Imports

In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
df = pd.read_csv("../datasets/raw/IndianWeatherRepository.csv")
print("Dataset Loaded Successfully")

Dataset Loaded Successfully

# Dataset Shape

In [2]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 119398
Columns: 42

# Missing Value Analysis

In [3]:
missing_values = df.isnull().sum()
missing_report = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": missing_values.values
})
missing_report

                          Column  Missing Values
0                        country               0
1                  location_name               0
2                         region               0
3                       latitude               0
4                      longitude               0
5                       timezone               0
6             last_updated_epoch               0
7                   last_updated               0
8            temperature_celsius               0
9         temperature_fahrenheit               0
10                condition_text               0
11                      wind_mph               0
12                      wind_kph               0
13                   wind_degree               0
14                wind_direction               0
15                   pressure_mb               0
16                   pressure_in               0
17                     precip_mm               0
18                     precip_in               0
19                      humidity               0
20                         cloud               0
21            feels_like_celsius               0
22         feels_like_fahrenheit               0
23                 visibility_km               0
24              visibility_miles               0
25                      uv_index               0
26                      gust_mph               0
27                      gust_kph               0
28   air_quality_Carbon_Monoxide               0
29             air_quality_Ozone               0
30  air_quality_Nitrogen_dioxide               0
31   air_quality_Sulphur_dioxide               0
32             air_quality_PM2.5               0
33              air_quality_PM10               0
34      air_quality_us-epa-index               0
35    air_quality_gb-defra-index               0
36                       sunrise               0
37                        sunset               0
38                      moonrise               0
39                       moonset               0
40                    moon_phase               0
41             moon_illumination               0

# Total Missing Values

In [4]:
total_missing = df.isnull().sum().sum()
print("Total Missing Values:", total_missing)

Total Missing Values: 0

# Duplicate Analysis

In [5]:
duplicates = df.duplicated().sum()
print("Duplicate Records:", duplicates)

Duplicate Records: 0

# Unique Value Analysis

In [6]:
unique_values = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": df.nunique().values
})
unique_values.sort_values(
    by="Unique Values"
)

                          Column  Unique Values
0                        country              1
5                       timezone              3
34      air_quality_us-epa-index              6
24              visibility_miles              7
40                    moon_phase              8
25                      uv_index              9
35    air_quality_gb-defra-index             10
14                wind_direction             16
2                         region             33
23                 visibility_km             44
10                condition_text             50
18                     precip_in             72
15                   pressure_mb             72
41             moon_illumination             92
19                      humidity             93
20                         cloud            101
11                      wind_mph            103
12                      wind_kph            103
16                   pressure_in            173
36                       sunrise            202
37                        sunset            215
13                   wind_degree            360
26                      gust_mph            363
29             air_quality_Ozone            384
30  air_quality_Nitrogen_dioxide            391
31   air_quality_Sulphur_dioxide            409
28   air_quality_Carbon_Monoxide            416
6             last_updated_epoch            432
4                      longitude            435
3                       latitude            455
17                     precip_mm            534
1                  location_name            552
27                      gust_kph            554
8            temperature_celsius            636
21            feels_like_celsius            695
7                   last_updated            877
9         temperature_fahrenheit           1056
22         feels_like_fahrenheit           1162
38                      moonrise           1441
39                       moonset           1441
32             air_quality_PM2.5           5078
33              air_quality_PM10           5561

# Constant Feature Detection

In [7]:
constant_features = [
    col
    for col in df.columns
    if df[col].nunique() == 1
]
print("Constant Features:")
print(constant_features)

Constant Features:
['country']

# Data Quality Report

In [8]:
print("""
DATA QUALITY REPORT
1. Missing Values: 0
2. Duplicate Records: 0
3. Dataset integrity verified
4. Constant features detected:
   - country
5. Dataset quality is excellent
6. No imputation required
7. No duplicate removal required
Dataset is ready for feature removal phase.
""")

DATA QUALITY REPORT
1. Missing Values: 0
2. Duplicate Records: 0
3. Dataset integrity verified
4. Constant features detected:
   - country
5. Dataset quality is excellent
6. No imputation required
7. No duplicate removal required
Dataset is ready for feature removal phase.